### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by prasad-kumkar** [ze-xe/contracts-0.1#12]
```
Error: VM Exception while processing transaction: reverted with reason string 'AccessControl: account 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 is missing role 0xa49807205ce4d355092ef5a8a18f56e8913cf4a201fbe287825b095693c21775'
    at Exchange._upgradeToAndCallUUPS (@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol:101)
    at Exchange.onlyRole (@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol:76)
    at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async HardhatNode._mineBlockWithPendingTxs (/Users/prasad/projects/synthex/zexe/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1802:23)
    at async HardhatNode.mineBlock (/Users/prasad/projects/synthex/zexe/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:491:16)
    at async EthModule._sendTransactionAndReturnHash (/Users/prasad/projects/synthex/zexe/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)

```

Steps to reproduce:

`npx hardhat run scripts`

**Comment by prasad-kumkar** [comment]
fixed in #13
